import "./globals.css";
import { Radio_Canada } from "next/font/google";
import { ContextProvider } from "@/context/store";
const inter = Radio_Canada({ subsets: ["latin"], display: "fallback" });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ContextProvider>
			<html lang="en">
				<body className={inter.className}>{children}</body>
				
			</html>
		</ContextProvider>
	);
}
